os: linux
dist: xenial
language: python
cache: pip
python:
- '3.7'
install:
- PIPENV_HIDE_EMOJIS=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true make install
script:
- make test
- make lint
- make mypy
- make check-dist
after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
stages:
- name: test
  if: type = pull_request OR branch = master OR tag IS present
- name: build
  if: type = push AND (branch = master OR tag IS present)
jobs:
  include:
  - stage: test
    python: 3.7
    name: 'Python: 3.7'
    before_script:
    - docker-compose up -d
    script:
    - make test
    after_script:
    - docker-compose down
  - stage: build
    name: PyPI Build and Upload
    python: 3.7
    services:
    - docker
    install: skip
    env:
    - PIP=pip
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    before_script:
    - pip install -U wheel
    - make clean
    script:
    - python setup.py sdist bdist_wheel
    after_success:
    - ls -lha dist
    deploy:
      provider: pypi
      skip_cleanup: true
      username: __token__
      password:
        secure: J0gT3Jp6GqWkTEopEx3GI6Dn35XGLL40wBgw86hdXrT0MlkxnwbYj9iB1XuB9/S7/e8x/92XJEfnOYej0upHRxFDwr8zcJZb4kegqY+XnUkAKVjWoBt6iCzdeVga2a1eDtKqxTXz+KT0E2iL3ErDMeYLYqRyvS+4dDws1KEqkZUYHDYQLwGn3QajFRsjrgdk2PfKcoY/m7PSDSmEuLHZ9i0/DyLn41LAZUqoR9ZKuSIwuVfqr28wqDvtG3UM8vrhsIhFKIJk7Ahh9HNy80z0T3aEQPnM9LNRGWbl5C9CN9OTawA820pwj8n95z/LUKu9k00AKB9dLn7E72NlrtdtONJKBtiwGh7OAkIwjBgCCgrnpLF0gCi5yxGdZ68ZbogAUMC9NS0NkSJVYEqubAOyqpZ2ubQDUjtjKqJKp88Xo/k9jZ6u1ZIY+GsXHVcc/PZ1hBrInRt5kxiAHwzCkdT6lV3Stg0HwLwcQRihKRJQk9h0p0xt4IBK1C8yctNuvoC1jzFHgfJxjoe4xQ1feQJQbVmzLXj6fZbqahBVl89el6mT9jPX1e7sd+JEAFIz6PZOH75iO7x6kgMI36S0A8bbqT3ZnHWTjKegoHTSNdPH4LkXs/y3HVsol4nB1Sj95n0iMsC+LlrduEaaYtFlH+yLO8E7e3eafv2bBEMU9RXJZKQ=
      on:
        tags: true
